const Data=[
            { id:'1',
              label:'Delhi',
             value:'Delhi Airport India',
            code:'DEL',},
            {id:'2',
              label:'Mumbai',
             value:'Chhatrapati Shivaji International Airport',
              code:'BOM',},
            {id:'3',
              label:'New-Delhi',
             value:'Indira Gandhi International Airport',
             code:'DEL',},
            {id:'4',
              label:'Bangkok',
            value:'Bangkok Thailand',
            code:'BKK',},
            {id:'5',
              label:'Bengaluru',
            value:'Bengaluru International Airport',
            code:'BLR',},
            {id:'6',
              label:'Pune',
            value:'Pune Airport',
            code:'PNQ',},
            {id:'7',
              label:'Hyderabad',
            value:'Rajiv Gandhi International Airport',
            code:'HYD',},
            {id:'8',
              label:'Kolkata',
             value:'Netaji Subhash Chandra Bose International Airport',
             code:'CCU',},
             {id:'9',
              label:'Goa',
             value:'Goa Dabolim International Airport',
             code:'GOI',},
             {id:'10',
              label:'Dubai',
             value:'Dubai International Airport',
             code:'DXB',}
           ];
           export default Data;