        const OfferDetails=[{id:'1',
                             name:'Grand Heritage',
                             image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/477540475.jpg?k=8d95643413e0959198c180aa324885cdafdd1995f4b4dad0ba407568dae07c46&o=&hp=1',
                             offer_detailOne:'Get upto 50% OFF*  ',
                             offer_detailTwo:'on Any Room Of  Grand Heritage Hotel',
                             expire_date:'31 Dec 2024',
                            },
                            {
                                id:'2',
                                name:'PUNE Trains',
                                image:'https://images5.alphacoders.com/442/thumb-1920-442528.jpg',
                                offer_detailOne:'Get upto 30% OFF*',
                                offer_detailTwo:'on Any Passenger Seat Of Cabin Class',
                                expire_date:'28 Jan 2025 ',
                            },
                            {
                                id:'3',
                                 name:'GOI  Flights',
                                image:'http://3.bp.blogspot.com/-FF8Ph4LNqAk/UA52r_kZXTI/AAAAAAAAH7s/b62RMOVZnXg/s1600/Airplane_aeroplane_aircraft_jet_wallpapers+(72).jpg',
                                offer_detailOne:'Get upto 50% OFF*',
                                offer_detailTwo:'on Any  Traveller Seat Of Cabin Class',
                                expire_date:'31 Dec 2024',
                            },
                            {
                                id:'4',
                                name:'SBC Trains',
                                image:'https://tse3.mm.bing.net/th?id=OIP.NhiHjBLl1xozCATBbVFcYwHaFC&pid=Api&P=0&h=180',
                                offer_detailOne:'Get upto 30% OFF*',
                                offer_detailTwo:'on Any Passenger Seat Of Cabin Class',
                                expire_date:'31 Mar 2025',
                                },
                                {
                                    id:'5',
                                     name:'Hyatt Regency',
                                    image:'https://pix8.agoda.net/hotelImages/139/1390143/1390143_17011402150050314638.jpg?ca=6&ce=1&s=800x',
                                    offer_detailOne:'Get upto 45% OFF*',
                                    offer_detailTwo:'on Any Room Of  Hyatt Regency',
                                    expire_date:'15 Jan 2025',
                                    },
                            {id:'6',
                                name:'DXB  Flights',
                                image:'https://tse2.mm.bing.net/th?id=OIP._3iCbSqUY50LpA02QBAz7wHaEK&pid=Api&P=0&h=180',
                                offer_detailOne:'Get upto 30% OFF*',
                                offer_detailTwo:'on Any  Traveller Seat Of Cabin Class ',
                                expire_date:'31 Mar 2025',
                                 },
                            {
                            id:'7',
                            name:'Courtyard Hotel',
                            image:'https://imgcld.yatra.com/ytimages/image/upload/t_seo_Hotel_w_930_h_550_c_fill_g_auto_q_40_f_jpg/v1475667608/Domestic%20Hotels/Hotels_Ludhiana/The%20Courtyard%20Hotel/Overview.jpg',
                            offer_detailOne:'Get upto 50% OFF*',
                            offer_detailTwo:'on Any Room Of  Courtyard Hotel',
                            expire_date:'01 Jan 2025',
                            },
                            {id:'8',
                                name:'PNBE Trains',
                                image:'https://tse2.mm.bing.net/th?id=OIP.bcOP7ZTpLAyyl3tKpdk5gAHaFB&pid=Api&P=0&h=180',
                                offer_detailOne:'Get upto 70% OFF*',
                                offer_detailTwo:'on Any Passenger Seat Of Cabin Class',
                                expire_date:'29 Dec 2024',
                                },
                                {
                                    id:'9',
                                    name:'BOM  Flights',
                                    image:'https://cdn.pixabay.com/photo/2016/11/18/16/34/aeroplane-1835690_960_720.jpg',
                                    offer_detailOne:'Get upto 80% OFF*',
                                    offer_detailTwo:'on Any Traveller Seat Of Cabin Class',
                                    expire_date:'28 Dec 2024',
                                    },
                            {
                            id:'10',
                            name:'MahaRaja Regency',
                            image:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/10/1d/82/hotel-maharaja-regency.jpg?w=1200&h=-1&s=1',
                            offer_detailOne:'Get upto 40% OFF*',
                            offer_detailTwo:'on Any Room Of  MahaRaja Regency',
                            expire_date:'31 Jan 2025',
                            },
                            {
                                id:'11',
                                name:'HWH Trains',
                                image:'https://tse1.mm.bing.net/th?id=OIP.UcNmQdG-siLwSInC3tX_AAHaE8&pid=Api&P=0&h=180',
                                offer_detailOne:'Get upto 60% OFF*',
                                offer_detailTwo:'on Any Passenger Seat Of Cabin Class',
                                expire_date:'01 Jan 2025',
                                },
                                {
                                    id:'12',
                                    name:'CCU  Flights',
                                    image:'https://compote.slate.com/images/222e0b84-f164-4fb1-90e7-d20bc27acd8c.jpg',
                                    offer_detailOne:'Get upto 60% OFF*',
                                    offer_detailTwo:'on Any Traveller Seat Of Cabin Class',
                                    expire_date:'22 Jan 2025',
                                    },
                            {
                            id:'13',
                            name:'Hotel Raai',
                            image:'https://cdn.halalstatic.com/expedia%2F107000000%2F106910000%2F106903400%2F106903356%2Ffb42907f_z.jpg?fit=bounds&format=jpg&width=750',
                            offer_detailOne:'Get upto 35% OFF*',
                            offer_detailTwo:'on Any Room Of Hotel Raai',
                            expire_date:'15 Feb 2025',
                            },
                            {
                                id:'14',
                                name:'NDLS Trains',
                                image:'https://tse2.mm.bing.net/th?id=OIP.CLo7grbkncWpUw4UuglUtwHaEK&pid=Api&P=0&h=180',
                                offer_detailOne:'Get upto 50% OFF*',
                                offer_detailTwo:'on Any Passenger Seat Of Cabin Class',
                                expire_date:'31 Dec 2024',
                                },
                            {
                            id:'15',
                            name:'DEL Flights',
                            image:'https://cdn.wallpapersafari.com/68/6/ISroup.jpg',
                            offer_detailOne:'Get upto 55% OFF*',
                            offer_detailTwo:'on Any Traveller Seat Of Cabin Class',
                            expire_date:'01 Feb 2025',
                            },
                            {
                                id:'16',
                                name:'Leela Palace',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/34213277.jpg?k=861b92672483a0d52762345308eb6da18f3b3da82fd6532280a5714c550e7719&o=&hp=1',
                                offer_detailOne:'Get upto 25% OFF*',
                                offer_detailTwo:'on Any Room Of Leela Palace',
                                expire_date:'15 Mar 2025',
                                }, {
                                 id:'17',
                                name:'Oberoi Hotel',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/31400560.jpg?k=7311c0e33dabdf7850add7ba6a502f64bb3a8c7bdc965360daeb806bc22eac45&o=&hp=1',
                                offer_detailOne:'Get upto 15% OFF*',
                                offer_detailTwo:'on Any Room Of Oberoi Hotel',
                                expire_date:'25 Mar 2025',
                                }, {
                                id:'18',
                                name:'Novotel Imagicaa',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/248087021.jpg?k=2c1e39293df86e67ef4e729c93bf2b619add47529185d8b4559bbc639afc87d1&o=&hp=1',
                                offer_detailOne:'Get upto 45% OFF*',
                                offer_detailTwo:'on Any Room Of Novotel Imagicaa',
                                expire_date:'15 Apr 2025',
                               }, {
                                id:'19',
                                name:'Grand Dragon',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/170109421.jpg?k=10fa7a904a2372eccb85866a16a863e9307af00c76998a4400aa357224d7adf2&o=&hp=1',
                                offer_detailOne:'Get upto 45% OFF*',
                                offer_detailTwo:'on Any Room Of Grand Dragon',
                                expire_date:'06 Feb 2025',
                                }, {
                                id:'20',
                                name:'Nidhivan Portico',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/61188603.jpg?k=e44ed1f004db4bf75fb16349fa3a2861cabb6348554f16f3862abe66f9fb6a96&o=&hp=1',
                                offer_detailOne:'Get upto 20% OFF*',
                                offer_detailTwo:'on Any Room Of Nidhivan Portico',
                                expire_date:'15 Apr 2025',
                                 }, {
                                 id:'21',
                                 name:'Khyber Resort',
                                 image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/17504266.jpg?k=73b762826d6b9de2a850c437e3ab69598d4aeccbbaf255053c5719198f9a7812&o=&hp=1',
                                offer_detailOne:'Get upto 12% OFF*',
                                offer_detailTwo:'on Any Room Of Khyber Resort',
                                expire_date:'15 Apr 2025',
                                }, {
                               id:'22',
                                name:'Aloft Hotel',
                                image:'https://cf.bstatic.com/xdata/images/hotel/max1024x768/626663383.jpg?k=99bdd5f8eb7271d7516a77b4b23964c7e544b55e8c639d1176144890119f25ab&o=&hp=1',
                                offer_detailOne:'Get upto 15% OFF*',
                                offer_detailTwo:'on Any Room Of Aloft Hotel',
                                expire_date:'05 Feb 2025',
                                },
                        ];
    export default OfferDetails;