const TrainData=[{id:'1',
                  city:'Delhi',
                  railway_station:'New Delhi Railway Station',
                  code:'NDLS',
                  },
                  {id:'2',
                city:'Kolkata',
                railway_station:'Kolkata Howrah Junction',
                code:'HWH',
                 },
                 {id:'3',
                 city:'Mumbai',
                 railway_station:'Kalyan Junction',
                code:'KYN',
                 },
                 {id:'4',
                city:'Chennai',
                railway_station:'Chennai Central Railway Station',
                code:'MAS',
                },
                {id:'5',
                 city:'Hyderabad',
                railway_station:'Secunderbad Junction',
                code:'SC',
                },
                {id:'6',
                city:'Bangalore',
                 railway_station:'Bangalore City Junction',
                code:'SBC',
                },
                {id:'7',
                city:'Pune',
                railway_station:'Pune Junction',
                code:'PUNE',
                },
                {id:'8',
                city:'Ahmedabad',
               railway_station:'Ahmedabad Junction',
               code:'ADI',
                },
               {id:'9',
              city:'Patna',
              railway_station:'Patna Junction',
             code:'PNBE',
             },
            {id:'10',
             city:'Jaipur',
             railway_station:'Jaipur Railway Junction',
             code:'SBC',
            },
                ];
    export default TrainData;